### PR TITLE
palette fix

### LINKED ISSUE #89: fix old theme palette artifacts
- [x] Inputs module
  - [x] inputs (focus state/hover)
  - [x] textarea
- [ ] button group active state
- [x] Dialogs module
  - [x] Alerts
  - [x] Tooltip
- .... if something more

### PR DESCRIPTION
**Pull request by DoRightt**

### CODE REVIEW

**Review by scDisorder — CHANGES_REQUESTED** [review]
https://github.com/rovergulf/ngx-slice-kit/blob/main/libs/ngx-slice-kit/src/lib/core/theme/theme.model.ts#L61-L63

must be required  
please, remove `?` symbols

**Review by scDisorder — DISMISSED** [review]

File: libs/ngx-slice-kit/src/lib/modals/dialog/dialog.component.ts [hunk 1]
```diff
@@ -94,7 +94,7 @@ export class DialogComponent implements OnInit, OnDestroy {
         this.closed.complete();
         if (this.escapeSub) {
             console.log('esc sub is on');
```
Comment (scDisorder) [inline libs/ngx-slice-kit/src/lib/modals/dialog/dialog.component.ts]: remove unnecessary console log

**Review by scDisorder — CHANGES_REQUESTED** [review]

**Review by scDisorder — APPROVED** [review]
